// Release task — runs electron-builder with `--publish always`, which packages AND
// uploads artifacts to the configured publish provider (GitHub Releases by default,
// generated by gulp/build-config from electron-manager.json's `releases` block).
//
// Auth: the GH_TOKEN env var (loaded from .env or CI secrets) authorizes the upload.
//
// Cross-platform behavior:
//   - macOS: signs + notarizes (via the afterSign hook) + uploads .dmg / .zip
//   - Linux: builds + uploads .AppImage / .deb (no signing)
//   - Windows: when EM_SKIP_WIN_SIGN=true (CI macOS/linux runners), this never runs the
//              Windows target. The dedicated windows-sign job in CI handles that path.
//
// For local single-platform release runs, electron-builder targets only the host OS by default.

const path    = require('path');
const jetpack = require('fs-jetpack');
const Manager = new (require('../../build.js'));

const logger = Manager.logger('release');

module.exports = function release(done) {
  const projectRoot = process.cwd();
  const config = path.join(projectRoot, 'dist', 'electron-builder.yml');

  if (!jetpack.exists(config)) {
    return done(new Error(`Missing ${config}. Run gulp/build-config first (it generates this file from electron-manager.json).`));
  }

  if (!process.env.GH_TOKEN) {
    logger.warn('GH_TOKEN not set — electron-builder will fail to publish to GitHub Releases.');
  }

  let builder;
  try {
    builder = Manager.require('electron-builder');
  } catch (e) {
    return done(new Error(`Could not resolve electron-builder: ${e.message}. Run \`npm i -D electron-builder\` in the consumer.`));
  }

  const relConfig = path.relative(projectRoot, config);
  logger.log(`Releasing via electron-builder (config=${relConfig}, publish=always)...`);

  builder.build({
    config,
    publish: 'always',
  })
    .then((artifacts) => {
      const list = (artifacts || []).map((a) => path.relative(projectRoot, a));
      logger.log(`Released ${list.length} artifact(s):`);
      list.forEach((a) => logger.log(`  • ${a}`));
      done();
    })
    .catch((e) => {
      logger.error(`Release failed: ${e.message}`);
      done(e);
    });
};
